meta_product_name: "Aspa Wellness"
meta_title: "Aspa Wellness - Amazing Wellness Experience"
meta_description: "Search, book, and live a unique experience.."
meta_image: "../app/asset/image/BUSINESS PITCH ASPA GROUP .png" # should exist in `app/assets/images/`
facebook_account: "@aspa_facebook_account"   # required for Facebook Cards
